---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false

suites:
  - name: default
    run_list:
      - recipe[kindle]
    attributes:
      mac_app_store:
        username: <%= ENV['APPLE_ID_USERNAME'] %>
        password: <%= ENV['APPLE_ID_PASSWORD'] %>
  - name: mac_direct_download
    run_list:
      - recipe[kindle_test::mac_direct_download]
    attributes:
