---
driver:
  name: localhost

platforms:
  - name: macosx
    driver:
      name: localhost

suites:
  - name: default
    run_list:
      - recipe[kindle]
    attributes:
      mac_app_store:
        username: <%= ENV['APPLE_ID_USERNAME'] %>
        password: <%= ENV['APPLE_ID_PASSWORD'] %>
    excludes: windows-2012
  - name: mac_direct_download
    run_list:
      - recipe[kindle_test::mac_direct_download]
    attributes:
    excludes: windows-2012
