language: objective-c

install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle install --without=development integration

before_script:
  # Pending ENV support in Kitchen's Rake tasks and not just the CLI
  - cp .kitchen.travis.yml .kitchen.local.yml

script:
  - chef exec rake
  # Run one suite locally, then uninstall and run the other
  - chef exec kitchen test mac-direct-download-macosx
  - rm -rf /Applications/Kindle.app
  - chef exec kitchen test default-macosx

after_script:

env:
  global:
    # - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
