matrix:
  fast_finish: true

branches:
  only:
    - master

install:
  - winrm quickconfig -q
  - cinst chefdk
  - SET PATH=C:\opscode\chefdk\bin;%PATH%

build_script:
  - chef exec bundle install

test_script:
  - cp .kitchen.appveyor.yml .kitchen.local.yml
  - chef exec rake
  - chef exec kitchen test
