version: "master-{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  matrix:
    - ruby_version: "200"

install:
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - SET SPEC_OPTS=--format progress
  - cp .kitchen.appveyor.yml .kitchen.local.yml
  - bundle exec rake
  - bundle exec kitchen test
